# Generated by Django 4.1.4 on 2023-03-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
